using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace JraVanRaceHorseTable.Migrations
{
    /// <inheritdoc />
    public partial class InitialCreate : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.CreateTable(
                name: "Races",
                columns: table => new
                {
                    Id = table.Column<int>(type: "int", nullable: false)
                        .Annotation("SqlServer:Identity", "1, 1"),
                    RecordSpec = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    DataKubun = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    MakeDate = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    Year = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    MonthDay = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    JyoCD = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    Kaiji = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    Nichiji = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    RaceNum = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    YoubiCD = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    TokuNum = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    Hondai = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    Fukudai = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    Kakko = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    HondaiEng = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    FukudaiEng = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    KakkoEng = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    Ryakusyo10 = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    Ryakusyo6 = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    Ryakusyo3 = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    Kubun = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    Nkai = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    GradeCD = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    GradeCDBefore = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    SyubetuCD = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    KigoCD = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    JyuryoCD = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    JyokenCD1 = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    JyokenCD2 = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    JyokenCD3 = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    JyokenCD4 = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    JyokenCD5 = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    JyokenName = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    Kyori = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    KyoriBefore = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    TrackCD = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    TrackCDBefore = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    CourseKubunCD = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    CourseKubunCDBefore = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    Honsyokin1 = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    Honsyokin2 = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    Honsyokin3 = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    Honsyokin4 = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    Honsyokin5 = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    Honsyokin6 = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    Honsyokin7 = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    HonsyokinBefore1 = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    HonsyokinBefore2 = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    HonsyokinBefore3 = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    HonsyokinBefore4 = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    HonsyokinBefore5 = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    Fukasyokin1 = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    Fukasyokin2 = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    Fukasyokin3 = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    Fukasyokin4 = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    Fukasyokin5 = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    FukasyokinBefore1 = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    FukasyokinBefore2 = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    FukasyokinBefore3 = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    HassoTime = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    HassoTimeBefore = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    TorokuTosu = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    SyussoTosu = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    NyusenTosu = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    TenkoCD = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    SibaBabaCD = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    DirtBabaCD = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    LapTime1 = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    LapTime2 = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    LapTime3 = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    LapTime4 = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    LapTime5 = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    LapTime6 = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    LapTime7 = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    LapTime8 = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    LapTime9 = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    LapTime10 = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    LapTime11 = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    LapTime12 = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    LapTime13 = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    LapTime14 = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    LapTime15 = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    LapTime16 = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    LapTime17 = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    LapTime18 = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    LapTime19 = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    LapTime20 = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    LapTime21 = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    LapTime22 = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    LapTime23 = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    LapTime24 = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    LapTime25 = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    SyogaiMileTime = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    HaronTimeS3 = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    HaronTimeS4 = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    HaronTimeL3 = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    HaronTimeL4 = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    Corner1 = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    Syukaisu1 = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    Jyuni1 = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    Corner2 = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    Syukaisu2 = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    Jyuni2 = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    Corner3 = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    Syukaisu3 = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    Jyuni3 = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    Corner4 = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    Syukaisu4 = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    Jyuni4 = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    RecordUpKubun = table.Column<string>(type: "nvarchar(max)", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_Races", x => x.Id);
                });

            migrationBuilder.CreateTable(
                name: "Umas",
                columns: table => new
                {
                    Id = table.Column<int>(type: "int", nullable: false)
                        .Annotation("SqlServer:Identity", "1, 1"),
                    RecordSpec = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    DataKubun = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    MakeDate = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    KettoNum = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    DelKubun = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    RegDate = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    DelDate = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    BirthDate = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    Bamei = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    BameiKana = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    BameiEng = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    ZaikyuFlag = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    Reserved = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    UmaKigoCD = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    SexCD = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    HinsyuCD = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    KeiroCD = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    Ketto3InfoHansyokuNum1 = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    Ketto3InfoBamei1 = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    Ketto3InfoHansyokuNum2 = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    Ketto3InfoBamei2 = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    Ketto3InfoHansyokuNum3 = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    Ketto3InfoBamei3 = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    Ketto3InfoHansyokuNum4 = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    Ketto3InfoBamei4 = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    Ketto3InfoHansyokuNum5 = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    Ketto3InfoBamei5 = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    Ketto3InfoHansyokuNum6 = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    Ketto3InfoBamei6 = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    Ketto3InfoHansyokuNum7 = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    Ketto3InfoBamei7 = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    Ketto3InfoHansyokuNum8 = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    Ketto3InfoBamei8 = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    Ketto3InfoHansyokuNum9 = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    Ketto3InfoBamei9 = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    Ketto3InfoHansyokuNum10 = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    Ketto3InfoBamei10 = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    Ketto3InfoHansyokuNum11 = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    Ketto3InfoBamei11 = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    Ketto3InfoHansyokuNum12 = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    Ketto3InfoBamei12 = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    Ketto3InfoHansyokuNum13 = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    Ketto3InfoBamei13 = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    Ketto3InfoHansyokuNum14 = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    Ketto3InfoBamei14 = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    TozaiCD = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    ChokyosiCode = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    ChokyosiRyakusyo = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    Syotai = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    BreederCode = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    BreederName = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    SanchiName = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    BanusiCode = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    BanusiName = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    RuikeiHonsyoHeiti = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    RuikeiHonsyoSyogai = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    RuikeiFukaHeichi = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    RuikeiFukaSyogai = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    RuikeiSyutokuHeichi = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    RuikeiSyutokuSyogai = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    SogoChakukaisu1 = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    SogoChakukaisu2 = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    SogoChakukaisu3 = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    SogoChakukaisu4 = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    SogoChakukaisu5 = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    SogoChakukaisu6 = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    ChuoChakukaisu1 = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    ChuoChakukaisu2 = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    ChuoChakukaisu3 = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    ChuoChakukaisu4 = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    ChuoChakukaisu5 = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    ChuoChakukaisu6 = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    Ba1Chakukaisu1 = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    Ba1Chakukaisu2 = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    Ba1Chakukaisu3 = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    Ba1Chakukaisu4 = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    Ba1Chakukaisu5 = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    Ba1Chakukaisu6 = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    Ba2Chakukaisu1 = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    Ba2Chakukaisu2 = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    Ba2Chakukaisu3 = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    Ba2Chakukaisu4 = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    Ba2Chakukaisu5 = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    Ba2Chakukaisu6 = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    Ba3Chakukaisu1 = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    Ba3Chakukaisu2 = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    Ba3Chakukaisu3 = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    Ba3Chakukaisu4 = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    Ba3Chakukaisu5 = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    Ba3Chakukaisu6 = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    Ba4Chakukaisu1 = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    Ba4Chakukaisu2 = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    Ba4Chakukaisu3 = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    Ba4Chakukaisu4 = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    Ba4Chakukaisu5 = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    Ba4Chakukaisu6 = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    Ba5Chakukaisu1 = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    Ba5Chakukaisu2 = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    Ba5Chakukaisu3 = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    Ba5Chakukaisu4 = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    Ba5Chakukaisu5 = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    Ba5Chakukaisu6 = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    Ba6Chakukaisu1 = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    Ba6Chakukaisu2 = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    Ba6Chakukaisu3 = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    Ba6Chakukaisu4 = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    Ba6Chakukaisu5 = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    Ba6Chakukaisu6 = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    Ba7Chakukaisu1 = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    Ba7Chakukaisu2 = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    Ba7Chakukaisu3 = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    Ba7Chakukaisu4 = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    Ba7Chakukaisu5 = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    Ba7Chakukaisu6 = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    Jyotai1Chakukaisu1 = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    Jyotai1Chakukaisu2 = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    Jyotai1Chakukaisu3 = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    Jyotai1Chakukaisu4 = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    Jyotai1Chakukaisu5 = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    Jyotai1Chakukaisu6 = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    Jyotai2Chakukaisu1 = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    Jyotai2Chakukaisu2 = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    Jyotai2Chakukaisu3 = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    Jyotai2Chakukaisu4 = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    Jyotai2Chakukaisu5 = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    Jyotai2Chakukaisu6 = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    Jyotai3Chakukaisu1 = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    Jyotai3Chakukaisu2 = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    Jyotai3Chakukaisu3 = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    Jyotai3Chakukaisu4 = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    Jyotai3Chakukaisu5 = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    Jyotai3Chakukaisu6 = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    Jyotai4Chakukaisu1 = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    Jyotai4Chakukaisu2 = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    Jyotai4Chakukaisu3 = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    Jyotai4Chakukaisu4 = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    Jyotai4Chakukaisu5 = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    Jyotai4Chakukaisu6 = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    Jyotai5Chakukaisu1 = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    Jyotai5Chakukaisu2 = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    Jyotai5Chakukaisu3 = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    Jyotai5Chakukaisu4 = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    Jyotai5Chakukaisu5 = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    Jyotai5Chakukaisu6 = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    Jyotai6Chakukaisu1 = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    Jyotai6Chakukaisu2 = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    Jyotai6Chakukaisu3 = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    Jyotai6Chakukaisu4 = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    Jyotai6Chakukaisu5 = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    Jyotai6Chakukaisu6 = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    Jyotai7Chakukaisu1 = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    Jyotai7Chakukaisu2 = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    Jyotai7Chakukaisu3 = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    Jyotai7Chakukaisu4 = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    Jyotai7Chakukaisu5 = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    Jyotai7Chakukaisu6 = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    Jyotai8Chakukaisu1 = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    Jyotai8Chakukaisu2 = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    Jyotai8Chakukaisu3 = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    Jyotai8Chakukaisu4 = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    Jyotai8Chakukaisu5 = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    Jyotai8Chakukaisu6 = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    Jyotai9Chakukaisu1 = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    Jyotai9Chakukaisu2 = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    Jyotai9Chakukaisu3 = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    Jyotai9Chakukaisu4 = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    Jyotai9Chakukaisu5 = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    Jyotai9Chakukaisu6 = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    Jyotai10Chakukaisu1 = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    Jyotai10Chakukaisu2 = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    Jyotai10Chakukaisu3 = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    Jyotai10Chakukaisu4 = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    Jyotai10Chakukaisu5 = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    Jyotai10Chakukaisu6 = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    Jyotai11Chakukaisu1 = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    Jyotai11Chakukaisu2 = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    Jyotai11Chakukaisu3 = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    Jyotai11Chakukaisu4 = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    Jyotai11Chakukaisu5 = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    Jyotai11Chakukaisu6 = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    Jyotai12Chakukaisu1 = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    Jyotai12Chakukaisu2 = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    Jyotai12Chakukaisu3 = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    Jyotai12Chakukaisu4 = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    Jyotai12Chakukaisu5 = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    Jyotai12Chakukaisu6 = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    Kyori1Chakukaisu1 = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    Kyori1Chakukaisu2 = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    Kyori1Chakukaisu3 = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    Kyori1Chakukaisu4 = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    Kyori1Chakukaisu5 = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    Kyori1Chakukaisu6 = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    Kyori2Chakukaisu1 = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    Kyori2Chakukaisu2 = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    Kyori2Chakukaisu3 = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    Kyori2Chakukaisu4 = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    Kyori2Chakukaisu5 = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    Kyori2Chakukaisu6 = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    Kyori3Chakukaisu1 = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    Kyori3Chakukaisu2 = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    Kyori3Chakukaisu3 = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    Kyori3Chakukaisu4 = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    Kyori3Chakukaisu5 = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    Kyori3Chakukaisu6 = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    Kyori4Chakukaisu1 = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    Kyori4Chakukaisu2 = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    Kyori4Chakukaisu3 = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    Kyori4Chakukaisu4 = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    Kyori4Chakukaisu5 = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    Kyori4Chakukaisu6 = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    Kyori5Chakukaisu1 = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    Kyori5Chakukaisu2 = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    Kyori5Chakukaisu3 = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    Kyori5Chakukaisu4 = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    Kyori5Chakukaisu5 = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    Kyori5Chakukaisu6 = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    Kyori6Chakukaisu1 = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    Kyori6Chakukaisu2 = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    Kyori6Chakukaisu3 = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    Kyori6Chakukaisu4 = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    Kyori6Chakukaisu5 = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    Kyori6Chakukaisu6 = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    Kyakusitu1 = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    Kyakusitu2 = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    Kyakusitu3 = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    Kyakusitu4 = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    RaceCount = table.Column<string>(type: "nvarchar(max)", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_Umas", x => x.Id);
                });

            migrationBuilder.CreateTable(
                name: "RaceUmas",
                columns: table => new
                {
                    Id = table.Column<int>(type: "int", nullable: false)
                        .Annotation("SqlServer:Identity", "1, 1"),
                    RaceId = table.Column<int>(type: "int", nullable: false),
                    RecordSpec = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    DataKubun = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    MakeDate = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    Wakuban = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    Umaban = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    KettoNum = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    Bamei = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    UmaKigoCD = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    SexCD = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    HinsyuCD = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    KeiroCD = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    Barei = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    TozaiCD = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    ChokyosiCode = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    ChokyosiRyakusyo = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    BanusiCode = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    BanusiName = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    Fukusyoku = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    reserved1 = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    Futan = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    FutanBefore = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    Blinker = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    reserved2 = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    KisyuCode = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    KisyuCodeBefore = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    KisyuRyakusyo = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    KisyuRyakusyoBefore = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    MinaraiCD = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    MinaraiCDBefore = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    BaTaijyu = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    ZogenFugo = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    ZogenSa = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    IJyoCD = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    NyusenJyuni = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    KakuteiJyuni = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    DochakuKubun = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    DochakuTosu = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    Time = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    ChakusaCD = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    ChakusaCDP = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    ChakusaCDPP = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    Jyuni1c = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    Jyuni2c = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    Jyuni3c = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    Jyuni4c = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    Odds = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    Ninki = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    Honsyokin = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    Fukasyokin = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    reserved3 = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    reserved4 = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    HaronTimeL4 = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    HaronTimeL3 = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    KettoNum1 = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    Bamei1 = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    KettoNum2 = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    Bamei2 = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    KettoNum3 = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    Bamei3 = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    TimeDiff = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    RecordUpKubun = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    DMKubun = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    DMTime = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    DMGosaP = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    DMGosaM = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    DMJyuni = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    KyakusituKubun = table.Column<string>(type: "nvarchar(max)", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_RaceUmas", x => x.Id);
                    table.ForeignKey(
                        name: "FK_RaceUmas_Races_RaceId",
                        column: x => x.RaceId,
                        principalTable: "Races",
                        principalColumn: "Id",
                        onDelete: ReferentialAction.Cascade);
                });

            migrationBuilder.CreateIndex(
                name: "IX_RaceUmas_RaceId",
                table: "RaceUmas",
                column: "RaceId");
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(
                name: "RaceUmas");

            migrationBuilder.DropTable(
                name: "Umas");

            migrationBuilder.DropTable(
                name: "Races");
        }
    }
}
