// <auto-generated />
using JraVanRaceHorseTable.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace JraVanRaceHorseTable.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20230926140943_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("JraVanRaceHorseTable.Models.Race", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Corner1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Corner2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Corner3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Corner4")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CourseKubunCD")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CourseKubunCDBefore")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DataKubun")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DirtBabaCD")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Fukasyokin1")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Fukasyokin2")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Fukasyokin3")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Fukasyokin4")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Fukasyokin5")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FukasyokinBefore1")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FukasyokinBefore2")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FukasyokinBefore3")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Fukudai")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FukudaiEng")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GradeCD")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GradeCDBefore")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HaronTimeL3")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HaronTimeL4")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HaronTimeS3")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HaronTimeS4")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HassoTime")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HassoTimeBefore")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Hondai")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HondaiEng")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Honsyokin1")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Honsyokin2")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Honsyokin3")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Honsyokin4")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Honsyokin5")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Honsyokin6")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Honsyokin7")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HonsyokinBefore1")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HonsyokinBefore2")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HonsyokinBefore3")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HonsyokinBefore4")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HonsyokinBefore5")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("JyoCD")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("JyokenCD1")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("JyokenCD2")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("JyokenCD3")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("JyokenCD4")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("JyokenCD5")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("JyokenName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Jyuni1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Jyuni2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Jyuni3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Jyuni4")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("JyuryoCD")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Kaiji")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Kakko")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KakkoEng")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KigoCD")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Kubun")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Kyori")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KyoriBefore")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LapTime1")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LapTime10")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LapTime11")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LapTime12")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LapTime13")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LapTime14")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LapTime15")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LapTime16")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LapTime17")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LapTime18")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LapTime19")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LapTime2")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LapTime20")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LapTime21")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LapTime22")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LapTime23")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LapTime24")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LapTime25")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LapTime3")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LapTime4")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LapTime5")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LapTime6")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LapTime7")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LapTime8")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LapTime9")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MakeDate")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MonthDay")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nichiji")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nkai")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NyusenTosu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RaceNum")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RecordSpec")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RecordUpKubun")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ryakusyo10")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ryakusyo3")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ryakusyo6")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SibaBabaCD")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SyogaiMileTime")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SyubetuCD")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Syukaisu1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Syukaisu2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Syukaisu3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Syukaisu4")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SyussoTosu")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenkoCD")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TokuNum")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TorokuTosu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TrackCD")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TrackCDBefore")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Year")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("YoubiCD")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Races");
                });

            modelBuilder.Entity("JraVanRaceHorseTable.Models.RaceUma", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BaTaijyu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Bamei")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Bamei1")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Bamei2")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Bamei3")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BanusiCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BanusiName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Barei")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Blinker")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ChakusaCD")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ChakusaCDP")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ChakusaCDPP")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ChokyosiCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ChokyosiRyakusyo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DMGosaM")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DMGosaP")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DMJyuni")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DMKubun")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DMTime")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DataKubun")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DochakuKubun")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DochakuTosu")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Fukasyokin")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Fukusyoku")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Futan")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FutanBefore")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HaronTimeL3")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HaronTimeL4")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HinsyuCD")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Honsyokin")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IJyoCD")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Jyuni1c")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Jyuni2c")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Jyuni3c")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Jyuni4c")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KakuteiJyuni")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KeiroCD")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KettoNum")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KettoNum1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KettoNum2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KettoNum3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KisyuCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KisyuCodeBefore")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KisyuRyakusyo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KisyuRyakusyoBefore")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KyakusituKubun")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MakeDate")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MinaraiCD")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MinaraiCDBefore")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ninki")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NyusenJyuni")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Odds")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RaceId")
                        .HasColumnType("int");

                    b.Property<string>("RecordSpec")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RecordUpKubun")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SexCD")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Time")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TimeDiff")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TozaiCD")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UmaKigoCD")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Umaban")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Wakuban")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ZogenFugo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ZogenSa")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("reserved1")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("reserved2")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("reserved3")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("reserved4")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("RaceId");

                    b.ToTable("RaceUmas");
                });

            modelBuilder.Entity("JraVanRaceHorseTable.Models.Uma", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Ba1Chakukaisu1")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ba1Chakukaisu2")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ba1Chakukaisu3")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ba1Chakukaisu4")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ba1Chakukaisu5")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ba1Chakukaisu6")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ba2Chakukaisu1")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ba2Chakukaisu2")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ba2Chakukaisu3")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ba2Chakukaisu4")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ba2Chakukaisu5")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ba2Chakukaisu6")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ba3Chakukaisu1")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ba3Chakukaisu2")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ba3Chakukaisu3")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ba3Chakukaisu4")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ba3Chakukaisu5")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ba3Chakukaisu6")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ba4Chakukaisu1")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ba4Chakukaisu2")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ba4Chakukaisu3")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ba4Chakukaisu4")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ba4Chakukaisu5")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ba4Chakukaisu6")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ba5Chakukaisu1")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ba5Chakukaisu2")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ba5Chakukaisu3")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ba5Chakukaisu4")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ba5Chakukaisu5")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ba5Chakukaisu6")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ba6Chakukaisu1")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ba6Chakukaisu2")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ba6Chakukaisu3")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ba6Chakukaisu4")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ba6Chakukaisu5")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ba6Chakukaisu6")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ba7Chakukaisu1")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ba7Chakukaisu2")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ba7Chakukaisu3")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ba7Chakukaisu4")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ba7Chakukaisu5")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ba7Chakukaisu6")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Bamei")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BameiEng")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BameiKana")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BanusiCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BanusiName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BirthDate")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BreederCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BreederName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ChokyosiCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ChokyosiRyakusyo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ChuoChakukaisu1")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ChuoChakukaisu2")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ChuoChakukaisu3")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ChuoChakukaisu4")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ChuoChakukaisu5")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ChuoChakukaisu6")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DataKubun")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DelDate")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DelKubun")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HinsyuCD")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Jyotai10Chakukaisu1")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Jyotai10Chakukaisu2")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Jyotai10Chakukaisu3")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Jyotai10Chakukaisu4")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Jyotai10Chakukaisu5")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Jyotai10Chakukaisu6")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Jyotai11Chakukaisu1")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Jyotai11Chakukaisu2")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Jyotai11Chakukaisu3")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Jyotai11Chakukaisu4")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Jyotai11Chakukaisu5")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Jyotai11Chakukaisu6")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Jyotai12Chakukaisu1")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Jyotai12Chakukaisu2")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Jyotai12Chakukaisu3")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Jyotai12Chakukaisu4")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Jyotai12Chakukaisu5")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Jyotai12Chakukaisu6")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Jyotai1Chakukaisu1")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Jyotai1Chakukaisu2")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Jyotai1Chakukaisu3")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Jyotai1Chakukaisu4")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Jyotai1Chakukaisu5")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Jyotai1Chakukaisu6")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Jyotai2Chakukaisu1")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Jyotai2Chakukaisu2")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Jyotai2Chakukaisu3")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Jyotai2Chakukaisu4")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Jyotai2Chakukaisu5")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Jyotai2Chakukaisu6")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Jyotai3Chakukaisu1")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Jyotai3Chakukaisu2")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Jyotai3Chakukaisu3")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Jyotai3Chakukaisu4")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Jyotai3Chakukaisu5")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Jyotai3Chakukaisu6")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Jyotai4Chakukaisu1")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Jyotai4Chakukaisu2")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Jyotai4Chakukaisu3")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Jyotai4Chakukaisu4")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Jyotai4Chakukaisu5")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Jyotai4Chakukaisu6")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Jyotai5Chakukaisu1")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Jyotai5Chakukaisu2")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Jyotai5Chakukaisu3")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Jyotai5Chakukaisu4")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Jyotai5Chakukaisu5")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Jyotai5Chakukaisu6")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Jyotai6Chakukaisu1")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Jyotai6Chakukaisu2")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Jyotai6Chakukaisu3")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Jyotai6Chakukaisu4")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Jyotai6Chakukaisu5")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Jyotai6Chakukaisu6")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Jyotai7Chakukaisu1")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Jyotai7Chakukaisu2")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Jyotai7Chakukaisu3")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Jyotai7Chakukaisu4")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Jyotai7Chakukaisu5")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Jyotai7Chakukaisu6")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Jyotai8Chakukaisu1")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Jyotai8Chakukaisu2")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Jyotai8Chakukaisu3")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Jyotai8Chakukaisu4")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Jyotai8Chakukaisu5")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Jyotai8Chakukaisu6")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Jyotai9Chakukaisu1")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Jyotai9Chakukaisu2")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Jyotai9Chakukaisu3")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Jyotai9Chakukaisu4")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Jyotai9Chakukaisu5")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Jyotai9Chakukaisu6")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KeiroCD")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ketto3InfoBamei1")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ketto3InfoBamei10")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ketto3InfoBamei11")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ketto3InfoBamei12")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ketto3InfoBamei13")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ketto3InfoBamei14")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ketto3InfoBamei2")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ketto3InfoBamei3")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ketto3InfoBamei4")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ketto3InfoBamei5")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ketto3InfoBamei6")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ketto3InfoBamei7")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ketto3InfoBamei8")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ketto3InfoBamei9")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ketto3InfoHansyokuNum1")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ketto3InfoHansyokuNum10")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ketto3InfoHansyokuNum11")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ketto3InfoHansyokuNum12")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ketto3InfoHansyokuNum13")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ketto3InfoHansyokuNum14")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ketto3InfoHansyokuNum2")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ketto3InfoHansyokuNum3")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ketto3InfoHansyokuNum4")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ketto3InfoHansyokuNum5")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ketto3InfoHansyokuNum6")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ketto3InfoHansyokuNum7")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ketto3InfoHansyokuNum8")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ketto3InfoHansyokuNum9")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KettoNum")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Kyakusitu1")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Kyakusitu2")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Kyakusitu3")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Kyakusitu4")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Kyori1Chakukaisu1")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Kyori1Chakukaisu2")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Kyori1Chakukaisu3")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Kyori1Chakukaisu4")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Kyori1Chakukaisu5")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Kyori1Chakukaisu6")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Kyori2Chakukaisu1")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Kyori2Chakukaisu2")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Kyori2Chakukaisu3")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Kyori2Chakukaisu4")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Kyori2Chakukaisu5")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Kyori2Chakukaisu6")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Kyori3Chakukaisu1")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Kyori3Chakukaisu2")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Kyori3Chakukaisu3")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Kyori3Chakukaisu4")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Kyori3Chakukaisu5")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Kyori3Chakukaisu6")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Kyori4Chakukaisu1")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Kyori4Chakukaisu2")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Kyori4Chakukaisu3")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Kyori4Chakukaisu4")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Kyori4Chakukaisu5")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Kyori4Chakukaisu6")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Kyori5Chakukaisu1")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Kyori5Chakukaisu2")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Kyori5Chakukaisu3")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Kyori5Chakukaisu4")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Kyori5Chakukaisu5")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Kyori5Chakukaisu6")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Kyori6Chakukaisu1")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Kyori6Chakukaisu2")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Kyori6Chakukaisu3")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Kyori6Chakukaisu4")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Kyori6Chakukaisu5")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Kyori6Chakukaisu6")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MakeDate")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RaceCount")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RecordSpec")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RegDate")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Reserved")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RuikeiFukaHeichi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RuikeiFukaSyogai")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RuikeiHonsyoHeiti")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RuikeiHonsyoSyogai")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RuikeiSyutokuHeichi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RuikeiSyutokuSyogai")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SanchiName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SexCD")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SogoChakukaisu1")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SogoChakukaisu2")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SogoChakukaisu3")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SogoChakukaisu4")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SogoChakukaisu5")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SogoChakukaisu6")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Syotai")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TozaiCD")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UmaKigoCD")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ZaikyuFlag")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Umas");
                });

            modelBuilder.Entity("JraVanRaceHorseTable.Models.RaceUma", b =>
                {
                    b.HasOne("JraVanRaceHorseTable.Models.Race", null)
                        .WithMany("RaceUmas")
                        .HasForeignKey("RaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("JraVanRaceHorseTable.Models.Race", b =>
                {
                    b.Navigation("RaceUmas");
                });
#pragma warning restore 612, 618
        }
    }
}
